### ISSUE TITLE
Is that possible to tag your yamllint with given release version?

### ISSUE THREAD

**Issue by xinzweb** [cytopia/docker-yamllint#10]
Thanks a lot for preparing this yamllint docker for community to use.

Just one feature request is that possible to add version tags to the releases? In this case, the new version 1.18.0 just released, but people were still use 1.17.0, and surprise to see a new release and changed behavior.

So far, I can only see `latest` and `latest-0.2` etc.

Really appreciate your help.

**Comment by cytopia** [comment]
@xinzweb sure. It's coming here: https://github.com/cytopia/docker-yamllint/pull/11
