### ISSUE TITLE
semantic versioning

### ISSUE THREAD

**Issue by 030** [cytopia/docker-yamllint#20]
Would it be possible to apply semantic versioning?

**Comment by cytopia** [comment]
Hi @030. What would be the benefit/advantage of that? And also do you mean for git or docker image tags?

**Comment by cytopia** [comment]
@030 going to close this due to inactivity. If you have a good reason for the semantic versioning, please do let me know and we can continue to discuss it.

**Comment by 030** [comment]
https://semver.org/#why-use-semantic-versioning
